config/routes.rb
Phase2::Application.routes.draw do
  resource :social_profile
  resource :brief_bio
  resource :profile do
    get :preview
  end
  resources :projects

  devise_for :mavericks

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :careers
  resources :contact_us

  root :to => 'home#index'

  match ':controller(/:action(/:id(.:format)))'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :maverick
  
  validates :dob,                     :presence => true
  validates :position,                :presence => true
  validates :zone_of_genius,          :presence => true
  validates :tech_tools,              :presence => true
  validates :residence,               :presence => true
  validates :phone,                   :presence => true
  validates :emergency_contact,       :presence => true
  validates :google_reader_feed_url,  :presence => true
  
  before_update :set_status_update_timestamp
  
  has_attached_file :picture,
    :storage => :s3,
    :s3_credentials => {
      :access_key_id     => SiteConfig.s3.access_key_id,
      :secret_access_key => SiteConfig.s3.secret_access_key
    },
    :path   => ":attachment/:id/:style/:basename.:extension",
    :bucket => SiteConfig.s3.bucket,
    :styles => { :medium => "149", :thumb => "38" }
    
  Paperclip.interpolates :normalized_file_name do |attachment, style|
    attachment.instance.normalized_file_name
  end

  def normalized_file_name
    "#{self.id}-#{self.picture_file_name.gsub( /[^a-zA-Z0-9_\.]/, '_')}" 
  end
  
  def tech_tools;  RDiscount.new(super) end
  
  def set_status_update_timestamp
    if status_changed?
      self.status_update_timestamp = Time.now
    end
  end
  
  def recent_readings(limit = 4)
    feed = Feedzirra::Feed.fetch_and_parse(google_reader_feed_url)
    feed.entries.collect do |entry|
      {
        :url     => entry.url,
        :title   => entry.title
      }
    end[0...limit] rescue []
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  layout "application", :except => [:preview]
  before_filter :except => [:new, :create] do
    @profile = current_maverick.profile
    unless @profile
      redirect_to new_profile_path
    end
  end
  
  def show
  end
  
  def new
    redirect_to profiles_path if current_maverick.profile
    @profile = Profile.new
  end
  
  def create
    @profile = Profile.new(
      {
        :maverick_id => current_maverick.id
      }.merge(params[:profile])
    )
    if @profile.save
      redirect_to profile_path
    else
      render :action => :new
    end
  end
  
  def update
    if @profile.update_attributes(params[:profile])
      redirect_to profile_path
    else
      render :action => :edit
    end
  end

  def preview
    @mavericks = Maverick.all_for_display
    @maverick = current_maverick
    render :layout => "site", :template => "home/index"
  end

end

app/views/profiles/_form.html.erb
<%= semantic_form_for(@profile, :url => profile_path, :multipart => true, :html => {:class => 'titleAbove'}) do |f| %>

  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs :information do %>
    <%= f.input :dob, :as => :date, :label => 'Date of birth', :end_year => 18.years.ago.year, :start_year => 100.years.ago.year %>
    <%= f.input :position, :label => 'Your position at Idyllic Software' %>
    <%= f.input :skype, :label => 'What is your skype name? (public)' %>
    <%= f.input :zone_of_genius,:label => 'What is your zone of genius. (Goto http://myezog.com/Home.html to find it out)' %>
    <%= f.input :tech_tools, :label => 'Technologies and Tools' %>
    <%= f.input :residence, :label => 'Where do you live? (private)'%>
    <%= f.input :phone %>
    <%= f.input :personal_email, :label => 'What is your Personal email address? (private)' %>
    <%= f.input :emergency_contact, :input_html => {:rows => 7}, :label => 'Mention atleast one emergency contact. (private)' %>
    <%= f.input :google_reader_feed_url, :label => 'We want to know what you read so go ahead and put in your google reader feed url here.' %>
    <%= f.input :picture, :as => :file %>
  <% end %>
  <%= f.submit %>

<% end %>

app/views/profiles/edit.html.erb
<% content_for :page_title do %>
  Edit profile
<% end %>

<div class="active_admin_content">
  <div class="main_content_wrapper">
    <div class="main_content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<% content_for :page_title do %>
  New profile
<% end %>

<%= render 'form' %>

app/views/profiles/show.html.erb
<% content_for :page_title do %>
  <%= current_maverick.name %>'s Profile
  <% if  !current_maverick.publish%>
    <span class="preview">
      <%= link_to "Preview", preview_profile_path, :target => "_blank" %>
    </span>
  <% end %>
<% end %>

<%= form_for(@profile, :url => profile_path, :html => {:class => 'statusForm'}) do |f| %>
  <h2>What are you doing?</h2>
  <%= f.text_field :status, :size => 144 %>
  <%= f.submit 'Update'%>
<% end %>

<table class="information left">
  <tr>
    <td>Maverick</td>
    <td class="value"><%= @profile.maverick.name %></td>
  </tr>
  <tr>
    <td>Dob</td>
    <td class="value"><%= @profile.dob %></td>
  </tr>
  <tr>
    <td>Position</td>
    <td class="value"><%= @profile.position %></td>
  </tr>
  <tr>
    <td>Skype</td>
    <td class="value"><%= @profile.skype %></td>
  </tr>
  <tr>
    <td>Zone of genius</td>
    <td class="value"><%= @profile.zone_of_genius %></td>
  </tr>
  <tr>
    <td>Tech tools</td>
    <td class="value"><%= @profile.tech_tools %></td>
  </tr>
  <tr>
    <td>Residence</td>
    <td class="value"><%= @profile.residence %></td>
  </tr>
  <tr>
    <td>Phone</td>
    <td class="value"><%= @profile.phone %></td>
  </tr>
  <tr>
    <td>Personal Email</td>
    <td class="value"><%= @profile.personal_email %></td>
  </tr>
  <tr>
    <td>Emergancy contact</td>
    <td class="value"><%= @profile.emergency_contact %></td>
  </tr>
  <tr>
    <td colspan="2"><%= link_to 'Edit', edit_profile_path, :class => 'linkButton' %></td>
  </tr>
</table>
<%= image_tag @profile.picture.url(:medium) %>