config/routes.rb
Phase2::Application.routes.draw do
  resource :social_profile
  resource :brief_bio
  resource :profile do
    get :preview
  end
  resources :projects

  devise_for :mavericks

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :careers
  resources :contact_us

  root :to => 'home#index'

  match ':controller(/:action(/:id(.:format)))'

end

app/models/social_profile.rb
class SocialProfile < ActiveRecord::Base
  belongs_to :maverick
end

app/controllers/social_profiles_controller.rb
class SocialProfilesController < InheritedResources::Base
  
  before_filter :except => [:new, :create] do
    @social_profile = current_maverick.social_profile
    unless @social_profile
      redirect_to new_social_profile_path
    end
  end
  
  def show
  end
  
  def new
    redirect_to social_profile_path if current_maverick.social_profile
    @social_profile = SocialProfile.new
  end
  
  def create
    @social_profile = SocialProfile.new(
      {
        :maverick_id => current_maverick.id
      }.merge(params[:social_profile])
    )
    if @social_profile.save
      redirect_to social_profile_path
    else
      render :action => :new
    end
  end
  
  def update
    if @social_profile.update_attributes(params[:social_profile])
      redirect_to social_profile_path
    else
      render :action => :edit
    end
  end
  
end

app/views/social_profiles/_form.html.erb
<%= semantic_form_for(@social_profile, :url => social_profile_path, :html => {:class => 'titleAbove'}) do |f| %>
  <% if @social_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@social_profile.errors.count, "error") %> prohibited this social_profile from being saved:</h2>

      <ul>
        <% @social_profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs :information do %>
    <%= f.input :twitter %>
    <%= f.input :facebook %>
    <%= f.input :linkedin %>
    <%= f.input :stackoverflow %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/social_profiles/edit.html.erb
<h1>Editing social profiles</h1>

<%= render 'form' %>

<%= link_to 'Back', social_profile_path %>

app/views/social_profiles/new.html.erb
<% content_for :page_title do %>
  New social profile
<% end %>

<%= render 'form' %>

app/views/social_profiles/show.html.erb
<% content_for :page_title do %>
  <%= current_maverick.name %>'s social profile
<% end %>

<table class="information">
  <tr>
    <td>Maverick:</td>
    <td class="value"><%= @social_profile.maverick.name %></td>
  </tr>

  <tr>
    <td>Twitter:</td>
    <td class="value"><%= @social_profile.twitter.blank? ? 'Not provided' : @social_profile.twitter %></td>
  </tr>

  <tr>
    <td>Facebook:</td>
    <td class="value"><%= @social_profile.facebook.blank? ? 'Not provided' : @social_profile.facebook %></td>
  </tr>

  <tr>
    <td>Linkedin:</td>
    <td class="value"><%= @social_profile.linkedin.blank? ? 'Not provided' : @social_profile.linkedin %></td>
  </tr>

  <tr>
    <td>Stackoverflow:</td>
    <td class="value"><%= @social_profile.stackoverflow.blank? ? 'Not provided' : @social_profile.stackoverflow %></td>
  </tr>
</table>

<%= link_to 'Edit', edit_social_profile_path, :class => 'linkButton' %> |
<%= link_to 'Back', profile_path, :class => 'linkButton'  %>