config/routes.rb
Phase2::Application.routes.draw do
  resource :social_profile
  resource :brief_bio
  resource :profile do
    get :preview
  end
  resources :projects

  devise_for :mavericks

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :careers
  resources :contact_us

  root :to => 'home#index'

  match ':controller(/:action(/:id(.:format)))'

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :maverick

  

  has_attached_file :screenshot,
    :storage => :s3,
    :s3_credentials => {
    :access_key_id     => SiteConfig.s3.access_key_id,
    :secret_access_key => SiteConfig.s3.secret_access_key
  },
    :path   => ":attachment/:id/:style/:basename.:extension",
    :bucket => SiteConfig.s3.bucket,
    :styles => { :medium => "640X472"}
    validates_attachment_presence :screenshot


  Paperclip.interpolates :normalized_file_name do |attachment, style|
    attachment.instance.normalized_file_name
  end

  def normalized_file_name
    "#{self.id}-#{self.screenshot_file_name.gsub( /[^a-zA-Z0-9_\.]/, '_')}" 
  end
  
  extend_attribute :description, :extend => MarkdownMethods
  
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  
  protected
  
  def begin_of_association_chain
    current_maverick
	end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= semantic_form_for(@project, :multipart => true,:html => {:class => 'titleAbove'}) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs :information do %>
    <%= f.input :name %>
    <%= f.input :url %>
    <%= f.input :description,:input_html => {:rows => 7} %>
    <%= f.input :screenshot, :as => :file %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/projects/edit.html.erb
<% content_for :page_title do %>
  Edit project
<% end %>

<%= render 'form' %>

app/views/projects/index.html.erb
<% content_for :page_title do %>
  Listing projects
<% end %>

<table class="information">
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Description</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.url %></td>
    <td><%= project.description.to_html.html_safe || 'Not provided' %></td>
    <td><%= link_to 'Show', project, :class => 'linkButton' %></td>
    <td><%= link_to 'Edit', edit_project_path(project), :class => 'linkButton' %></td>
    <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete, :class => 'redLinkButton' %></td>
  </tr>
<% end %>
</table>


<%= link_to 'New Project', new_project_path, :class => 'linkButton' %>

app/views/projects/new.html.erb
<% content_for :page_title do %>
  New project
<% end %>

<%= render 'form' %>

app/views/projects/show.html.erb
<% content_for :page_title do %>
  Showing project - <%= @project.name %>
<% end %>
<p id="notice"><%= notice %></p>

<table class="information">
  <tr>
    <td>Name:</td>
    <td><%= @project.name %></td>
  </tr>

  <tr>
    <td>Url:</td>
    <td><%= @project.url %></td>
  </tr>

  <tr>
    <td>Description:</td>
    <td><%= @project.description %></td>
  </tr>
</table>

<%= link_to 'Edit', edit_project_path(@project), :class => 'linkButton' %> |
<%= link_to 'Back', project_path, :class => 'linkButton'  %>